const actionsType = {
  ADD_USER: 'ADD_USER',
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
  ADD_USER_FAIL: 'ADD_USER_FAIL',
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNIN_USER_FAIL: 'SIGNIN_USER_FAIL',
};

export default actionsType;
