const actionsType = {
  SIGNUP_USER: 'SIGNUP_USER',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAIL: 'SIGNUP_USER_FAIL',
  SIGNIN_USER: 'SIGNIN_USER',
  SIGNIN_USER_SUCCESS: 'SIGNIN_USER_SUCCESS',
  SIGNIN_USER_FAIL: 'SIGNIN_USER_FAIL',
};

export default actionsType;
